name: Front-Prod build & deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build
      env:
        KAKAO_API_KEY: ${{ secrets.KAKAO_API_KEY_PROD }}
        KAKAO_REDIRECT_URI: ${{ secrets.KAKAO_REDIRECT_URI_PROD }}
        NEXT_PUBLIC_SERVER_URL: ${{ secrets.NEXT_PUBLIC_SERVER_URL_PROD }}
        NEXT_PUBLIC_SELF_URL: ${{ secrets.NEXT_PUBLIC_SELF_URL_PROD }}
        NEXT_PUBLIC_BASE_URL: ${{ secrets.NEXT_PUBLIC_BASE_URL_PROD }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN_PROD }}
        NEXT_PUBLIC_SENTRY_DSN: ${{ secrets.NEXT_PUBLIC_SENTRY_DSN_PROD }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: TopazKang
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build Docker image
      run: |
        docker build \
        --build-arg KAKAO_API_KEY=${{ secrets.KAKAO_API_KEY_PROD }} \
        --build-arg KAKAO_REDIRECT_URI=${{ secrets.KAKAO_REDIRECT_URI_PROD }} \
        --build-arg NEXT_PUBLIC_SERVER_URL=${{ secrets.NEXT_PUBLIC_SERVER_URL_PROD }} \
        --build-arg NEXT_PUBLIC_SELF_URL=${{ secrets.NEXT_PUBLIC_SELF_URL_PROD }} \
        --build-arg NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL_PROD }} \
        --build-arg SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN_PROD }} \
        --build-arg NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN_PROD }} \
        -t ghcr.io/topazkang/fe-prod:latest .

    - name: Push Docker image to GHCR
      run: docker push ghcr.io/topazkang/fe-prod:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: SSH and Deploy Frontend
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST_PROD }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.ARK_DEPLOY }}
          port: 22
          script: |
            echo "${{ secrets.ENV_FILE_PROD }}" > deploy/front/.env
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GIT_USER }} --password-stdin
            cd deploy/front
            docker image prune -a -f
            docker-compose -f docker-compose.front.yaml down
            docker-compose -f docker-compose.front.yaml pull
            docker-compose -f docker-compose.front.yaml up -d
